### ISSUE TITLE
Feature Request: Better Thread Reading

### ISSUE THREAD

**Issue by ntorba** [rooteco/tweetscape#404] opened 2022-04-20 19:01 UTC
We need to enable users to expand tweets to show a full thread (whether it is the first tweet in a thread or in the middle). Here is an example in the screenshot: 

![image](https://user-images.githubusercontent.com/32570754/164302810-51f5e9a3-634e-4a77-aaf3-ac90530edfde.png)

Here is the link to that tweet from Timeless Box: https://twitter.com/UntilTrees/status/1516847183584276480?s=20&t=Kv2TbeequS-rBS9JDfSYww

It is the last tweet in a thread, but I had to click into the twitter UI to know that and to be able to read the tweets leading up to it. 

It would an indicator that a tweet is part of a thread, and a button to expand above or below that current tweet to show the rest of the thread. I think it would be best if the thread was shown in a scrollable window and replies were still shown under it. 

Replies will also be a bit tricky, because people reply to many different tweets in a thread. From what I've seen, many people like to reply to the first one, but I usually like to reply to one related to my comment. We will have to experiment with a couple of different options

**Comment by nicholaschiang** [comment] 2022-04-20 21:17
Duplicate of #383.

**Closed by nicholaschiang** 2022-04-20 21:17 UTC
Labels: Feature, High, E16
